baseURL = 'https://hiahia.art/'
languageCode = 'en-us'
title = 'Hia Hia Art'
theme = 'risotto'
author = "Max B"

sectionPagesMenu = "posts"


[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

[menu]

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

[markup.goldmark.renderer]
unsafe = true